baseURL = 'https://botoxx.github.io/'
languageCode = 'en-us'
title = 'Botond Geiszt'
disableKinds = ['taxonomy', 'taxonomyTerm']
enableEmoji = true

[params]
  description = "DevOps Engineer with cloud-native expertise"
  author = "Botond Geiszt"
  github = "https://github.com/botoxx"
  linkedin = "https://www.linkedin.com/in/botond-geiszt-82b91b167/"
  email = "botond@codenomads.io"
  jobtitle = "DevOps Engineer"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
